# Generated by Django 2.2.2 on 2019-12-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.BigIntegerField(default='', primary_key=True, serialize=False)),
                ('grp', models.CharField(default='NaN', max_length=100)),
                ('raw_content', models.TextField(default='NaN', max_length=200)),
                ('content', models.TextField(default='NaN', max_length=200)),
                ('screen_name', models.CharField(default='NaN', max_length=100)),
                ('valence', models.FloatField(default=0.0)),
                ('valence_seq', models.TextField(default='NaN', max_length=200)),
                ('valence_seq_rank', models.BigIntegerField(default=0)),
                ('valence_pred', models.FloatField(default=0.0)),
                ('valence_grp_pred', models.BigIntegerField(default=0)),
                ('dominance', models.FloatField(default=0.0)),
                ('dominance_seq', models.TextField(default='NaN', max_length=200)),
                ('dominance_seq_rank', models.BigIntegerField(default=0)),
                ('dominance_pred', models.FloatField(default=0.0)),
                ('dominance_grp_pred', models.BigIntegerField(default=0)),
                ('care', models.BigIntegerField(default=0)),
                ('care_seq', models.TextField(default='NaN', max_length=200)),
                ('care_seq_rank', models.BigIntegerField(default=0)),
                ('care_pred', models.BigIntegerField(default=0)),
                ('care_grp_pred', models.BigIntegerField(default=0)),
                ('care_prob', models.FloatField(default=0.0)),
                ('fairness', models.BigIntegerField(default=0)),
                ('fairness_seq', models.TextField(default='NaN', max_length=200)),
                ('fairness_seq_rank', models.BigIntegerField(default=0)),
                ('fairness_pred', models.BigIntegerField(default=0)),
                ('fairness_grp_pred', models.BigIntegerField(default=0)),
                ('fairness_prob', models.FloatField(default=0.0)),
                ('purity', models.BigIntegerField(default=0)),
                ('purity_seq', models.TextField(default='NaN', max_length=200)),
                ('purity_seq_rank', models.BigIntegerField(default=0)),
                ('purity_pred', models.BigIntegerField(default=0)),
                ('purity_grp_pred', models.BigIntegerField(default=0)),
                ('purity_prob', models.FloatField(default=0.0)),
                ('loyalty', models.BigIntegerField(default=0)),
                ('loyalty_seq', models.TextField(default='NaN', max_length=200)),
                ('loyalty_seq_rank', models.BigIntegerField(default=0)),
                ('loyalty_pred', models.BigIntegerField(default=0)),
                ('loyalty_grp_pred', models.BigIntegerField(default=0)),
                ('loyalty_prob', models.FloatField(default=0.0)),
                ('authority', models.BigIntegerField(default=0)),
                ('authority_seq', models.TextField(default='NaN', max_length=200)),
                ('authority_seq_rank', models.BigIntegerField(default=0)),
                ('authority_pred', models.BigIntegerField(default=0)),
                ('authority_grp_pred', models.BigIntegerField(default=0)),
                ('authority_prob', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('screen_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('num_followers', models.BigIntegerField(null=True)),
                ('num_friends', models.BigIntegerField(null=True)),
                ('num_tweets', models.BigIntegerField(null=True)),
                ('num_retweeted', models.BigIntegerField(null=True)),
                ('num_tweets_in_dataset', models.BigIntegerField(null=True)),
                ('lib_ratio', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
