# Generated by Django 2.2.2 on 2019-08-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('grp', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(max_length=200, null=True)),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('valence', models.FloatField(null=True)),
                ('arousal', models.FloatField(null=True)),
                ('dominance', models.FloatField(null=True)),
                ('moral1', models.FloatField(null=True)),
                ('moral2', models.FloatField(null=True)),
                ('moral3', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=100, null=True)),
                ('num_followers', models.BigIntegerField(null=True)),
                ('num_friends', models.BigIntegerField(null=True)),
                ('num_tweets', models.BigIntegerField(null=True)),
                ('num_retweeted', models.BigIntegerField(null=True)),
                ('bot_score', models.FloatField(blank=True, null=True)),
                ('num_tweets_in_dataset', models.BigIntegerField(null=True)),
                ('lib_ratio', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
