# Generated by Django 2.2.2 on 2019-07-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='id',
        ),
        migrations.AddField(
            model_name='tweet',
            name='arousal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='bot_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='content',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='dominance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='moral1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='moral2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='moral3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='num_followers',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='num_friends',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='num_retweeted',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='num_tweets',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='screen_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='valence',
            field=models.FloatField(null=True),
        ),
    ]
