# Generated by Django 2.2.2 on 2019-08-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='arousal',
            new_name='dominance',
        ),
    ]
