# Generated by Django 2.2.2 on 2019-08-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='screen_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
