# Generated by Django 2.2.2 on 2019-07-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20190723_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='group',
            new_name='grp',
        ),
    ]
