# Generated by Django 2.2.2 on 2019-08-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20190813_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='dominance_grp_pred',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='dominance_pred',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='dominance_seq',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='dominance_seq_rank',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='fairness_grp_pred',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='fairness_pred',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='fairness_prob',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='fairness_seq',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='fairness_seq_rank',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='harm_grp_pred',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='harm_pred',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='harm_prob',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='harm_seq',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='harm_seq_rank',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='valence_grp_pred',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='valence_pred',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='valence_seq',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='valence_seq_rank',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='fairness',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='harm',
            field=models.BigIntegerField(null=True),
        ),
    ]
