# Generated by Django 2.2.2 on 2019-12-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20191204_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='idx',
            field=models.BigIntegerField(default=0),
        ),
    ]
