# Generated by Django 2.2.2 on 2019-08-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20190817_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(default='NaN', max_length=200),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='dominance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='dominance_grp_pred',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='dominance_pred',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='dominance_seq',
            field=models.TextField(default='NaN', max_length=200),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='dominance_seq_rank',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='fairness',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='fairness_grp_pred',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='fairness_pred',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='fairness_prob',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='fairness_seq',
            field=models.TextField(default='NaN', max_length=200),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='fairness_seq_rank',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='grp',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='harm',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='harm_grp_pred',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='harm_pred',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='harm_prob',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='harm_seq',
            field=models.TextField(default='NaN', max_length=200),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='harm_seq_rank',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='screen_name',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='valence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='valence_grp_pred',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='valence_pred',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='valence_seq',
            field=models.TextField(default='NaN', max_length=200),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='valence_seq_rank',
            field=models.BigIntegerField(default=0),
        ),
    ]
