# Generated by Django 2.2.2 on 2019-12-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='idx',
            new_name='tweet_idx',
        ),
    ]
