# Generated by Django 2.2.2 on 2019-08-19 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20190818_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='harm',
            new_name='care',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='harm_grp_pred',
            new_name='care_grp_pred',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='harm_pred',
            new_name='care_pred',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='harm_prob',
            new_name='care_prob',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='harm_seq',
            new_name='care_seq',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='harm_seq_rank',
            new_name='care_seq_rank',
        ),
    ]
