# Generated by Django 2.2.2 on 2020-05-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20191204_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='care_seq_rank',
            field=models.FloatField(default=0),
        ),
    ]
