# Generated by Django 2.2.2 on 2020-05-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20200522_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
